export const Clubs = [
  { id: 1, name: '원티드', clubImg: 'Wanted.png' },
  { id: 2, name: '강남대학교', clubImg: 'kangnam.png' },
  { id: 3, name: '토스', clubImg: 'Toss.png' },
  { id: 4, name: '뉴테크서비스', clubImg: 'NtechService.png' },
  { id: 5, name: '샌드버드', clubImg: 'sendBird.png' },
  { id: 6, name: '챌린저스', clubImg: 'challenger.png' },
  { id: 7, name: '강남대학교', clubImg: 'kangnam.png' },
  { id: 8, name: '토스', clubImg: 'Toss.png' },
  { id: 9, name: '뉴테크서비스', clubImg: 'NtechService.png' },
  { id: 10, name: '원티드', clubImg: 'Wanted.png' },
  { id: 11, name: '챌린저스', clubImg: 'challenger.png' },
  { id: 12, name: '샌드버드', clubImg: 'sendBird.png' },
  { id: 13, name: '강남대학교', clubImg: 'kangnam.png' },
  { id: 14, name: '토스', clubImg: 'Toss.png' },
  { id: 15, name: '샌드버드', clubImg: 'sendBird.png' },
  { id: 16, name: '원티드', clubImg: 'Wanted.png' },
  { id: 17, name: '뉴테크서비스', clubImg: 'NtechService.png' },
  { id: 18, name: '강남대학교', clubImg: 'kangnam.png' },
];
