const describe = `
<h1>개편 이전의 고민</h1>
<p>토스는 다양한 직군의 사람들이 하나의 서비스를 만들기 위해 구성된 '사일로'와 토스 전체의 일관된 경험을 위해 같은 직군끼리 모인 '챕터'로 조직되어 있는데요. 모든 팀이 '쉽고 간편한 사용자 경험을 만들자’라는 공동의 목표를 가지고 있지만, 각자의 방식으로 Focus on impact를 하다 보니 전체 디자인에 통일성이 결여된 상황이 발생했습니다. 컴포넌트의 컬러에서부터, 폰트 크기, 문구까지 제품마다 다르게 사용되고 있었는데요. 이 때문에 디자인할 때마다 매번 어떤 컴포넌트를 사용할지 고민하는 문제가 생겼습니다. 빨리 달리며 했던 일들이 이제는 발목을 잡는 상황이 된 것이죠. 누군가가 좋은 디자인을 해도 프로덕트 전체로 확장되지 못하고 정체되어 있다는 느낌을 받았습니다. 모두에게 자율과 권한, 책임이 주어져 있지만 서로가 다른 방향으로 달려나가고 있다는 점이 고민이었습니다.</p>

<h1>조직 개편</h1>
<p>다른 애자일 조직도 분명 유사한 어려움이 있었을 것이라 생각해 찾던 중, 스포티파이가 유사한 문제를 경험하고 해결했음을 알게 되었습니다.</p>

<h1>디자인 개편</h1>
<p>토스 팀은 앞서 언급했던 것처럼, Focus on impact를 고민하며 큰 효과를 낼 수 있는 제품에 집중해왔습니다. 그렇다 보니 자동이체와 같이 성과가 나지 않는 페이지들은 계속해서 백로그에 남아있게 되었습니다. 탭 구조 또한 맥락을 갖고 있거나 서로 연결되어 도움을 주는 구조가 아니었습니다. 간편 송금에서 시작하여 추가된 기능들이 출시된 순서대로 탭에 추가되어있는 상태였는데요. 맥락이 튼튼한 구조를 갖추고자 전체 개편을 진행하게 되었습니다. 이는 속도를 내기 위해 쌓아 두었던 디자인 부채를 해결하기 위한 선택이었습니다. 전체 개편을 통해 사용자에게 가치를 줄 수 있는 부분에 투자하여 더 큰 가치를 창출할 수 있는 기반을 마련한 것이라 할 수 있습니다.</p>
`;

export const teamInfoBoxs = [
  {
    field: '프론트엔드',
    crew: [
      { name: '김멋사', role: '레이아웃 설계' },
      { name: '김멋사', role: '레이아웃 설계' },
    ],
  },
  {
    field: '프론트엔드',
    crew: [
      { name: '김멋사', role: '레이아웃 설계' },
      { name: '김멋사', role: '레이아웃 설계' },
    ],
  },
  {
    field: '프론트엔드',
    crew: [
      { name: '김멋사', role: '레이아웃 설계' },
      { name: '김멋사', role: '레이아웃 설계' },
    ],
  },
  {
    field: '프론트엔드',
    crew: [
      { name: '김멋사', role: '레이아웃 설계' },
      { name: '김멋사', role: '레이아웃 설계' },
    ],
  },
];

export const ProjectPreview = [
  {
    id: 1,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    thumbnail: 'https://i.ibb.co/yktPkxP/image-5.png',
  },
  {
    id: 2,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    thumbnail: 'https://i.ibb.co/yktPkxP/image-5.png',
  },
  {
    id: 3,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    thumbnail: 'https://i.ibb.co/yktPkxP/image-5.png',
  },
  {
    id: 4,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    thumbnail: 'https://i.ibb.co/yktPkxP/image-5.png',
  },
  {
    id: 5,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    thumbnail: 'https://i.ibb.co/yktPkxP/image-5.png',
  },
  {
    id: 6,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    thumbnail: 'https://i.ibb.co/yktPkxP/image-5.png',
  },
  {
    id: 7,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    thumbnail: 'https://i.ibb.co/yktPkxP/image-5.png',
  },
  {
    id: 8,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    thumbnail: 'https://i.ibb.co/yktPkxP/image-5.png',
  },
  {
    id: 9,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    thumbnail: 'https://i.ibb.co/yktPkxP/image-5.png',
  },
  {
    id: 10,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    thumbnail: 'https://i.ibb.co/yktPkxP/image-5.png',
  },
  {
    id: 11,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    thumbnail: 'https://i.ibb.co/yktPkxP/image-5.png',
  },
  {
    id: 12,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    thumbnail: 'https://i.ibb.co/yktPkxP/image-5.png',
  },
];
export const ProjectDetail = [
  {
    id: 1,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    image: 'ProjectDetail.png',
    club: '토스 프로덕트 팀',
    serviceType: '웹 서비스',
    projectState: '서비스 진행중',
    projectPeriod: '2022.02.01 ~ 2023.08.09',
    techStack: 'React · TypeScript · Next · SpringBoot · Mysql ',
    describe,
    teamInfoBoxs,
    projectLink: [
      { url: 'https://github.com/', icon: 'github' },
      { url: 'https://figma.com/', icon: 'figma' },
      { url: 'https://naver.com/', icon: 'other' },
    ],
  },
  {
    id: 2,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    image: 'ProjectDetail.png',
    club: '토스 프로덕트 팀',
    serviceType: '웹 서비스',
    projectState: '서비스 진행중',
    projectPeriod: '2022.02.01 ~ 2023.08.09',
    techStack: 'React · TypeScript · Next · SpringBoot · Mysql ',
    describe,
    teamInfoBoxs,
    projectLink: [
      { url: 'https://github.com/', icon: 'github' },
      { url: 'https://figma.com/', icon: 'figma' },
      { url: 'https://naver.com/', icon: 'other' },
    ],
  },
  {
    id: 3,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    image: 'ProjectDetail.png',
    club: '토스 프로덕트 팀',
    serviceType: '웹 서비스',
    projectState: '서비스 진행중',
    projectPeriod: '2022.02.01 ~ 2023.08.09',
    techStack: 'React · TypeScript · Next · SpringBoot · Mysql ',
    describe,
    teamInfoBoxs,
    projectLink: [
      { url: 'https://github.com/', icon: 'github' },
      { url: 'https://figma.com/', icon: 'figma' },
      { url: 'https://naver.com/', icon: 'other' },
    ],
  },
  {
    id: 4,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    image: 'ProjectDetail.png',
    club: '토스 프로덕트 팀',
    serviceType: '웹 서비스',
    projectState: '서비스 진행중',
    projectPeriod: '2022.02.01 ~ 2023.08.09',
    techStack: 'React · TypeScript · Next · SpringBoot · Mysql ',
    describe,
    teamInfoBoxs,
    projectLink: [
      { url: 'https://github.com/', icon: 'github' },
      { url: 'https://figma.com/', icon: 'figma' },
      { url: 'https://naver.com/', icon: 'other' },
    ],
  },
  {
    id: 5,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    image: 'ProjectDetail.png',
    club: '토스 프로덕트 팀',
    serviceType: '웹 서비스',
    projectState: '서비스 진행중',
    projectPeriod: '2022.02.01 ~ 2023.08.09',
    techStack: 'React · TypeScript · Next · SpringBoot · Mysql ',
    describe,
    teamInfoBoxs,
    projectLink: [
      { url: 'https://github.com/', icon: 'github' },
      { url: 'https://figma.com/', icon: 'figma' },
      { url: 'https://naver.com/', icon: 'other' },
    ],
  },
  {
    id: 6,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    image: 'ProjectDetail.png',
    club: '토스 프로덕트 팀',
    serviceType: '웹 서비스',
    projectState: '서비스 진행중',
    projectPeriod: '2022.02.01 ~ 2023.08.09',
    techStack: 'React · TypeScript · Next · SpringBoot · Mysql ',
    describe,
    teamInfoBoxs,
    projectLink: [
      { url: 'https://github.com/', icon: 'github' },
      { url: 'https://figma.com/', icon: 'figma' },
      { url: 'https://naver.com/', icon: 'other' },
    ],
  },
  {
    id: 7,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    image: 'ProjectDetail.png',
    club: '토스 프로덕트 팀',
    serviceType: '웹 서비스',
    projectState: '서비스 진행중',
    projectPeriod: '2022.02.01 ~ 2023.08.09',
    techStack: 'React · TypeScript · Next · SpringBoot · Mysql ',
    describe,
    teamInfoBoxs,
    projectLink: [
      { url: 'https://github.com/', icon: 'github' },
      { url: 'https://figma.com/', icon: 'figma' },
      { url: 'https://naver.com/', icon: 'other' },
    ],
  },
  {
    id: 8,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    image: 'ProjectDetail.png',
    club: '토스 프로덕트 팀',
    serviceType: '웹 서비스',
    projectState: '서비스 진행중',
    projectPeriod: '2022.02.01 ~ 2023.08.09',
    techStack: 'React · TypeScript · Next · SpringBoot · Mysql ',
    describe,
    teamInfoBoxs,
    projectLink: [
      { url: 'https://github.com/', icon: 'github' },
      { url: 'https://figma.com/', icon: 'figma' },
      { url: 'https://naver.com/', icon: 'other' },
    ],
  },
  {
    id: 9,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    image: 'ProjectDetail.png',
    club: '토스 프로덕트 팀',
    serviceType: '웹 서비스',
    projectState: '서비스 진행중',
    projectPeriod: '2022.02.01 ~ 2023.08.09',
    techStack: 'React · TypeScript · Next · SpringBoot · Mysql ',
    describe,
    teamInfoBoxs,
    projectLink: [
      { url: 'https://github.com/', icon: 'github' },
      { url: 'https://figma.com/', icon: 'figma' },
      { url: 'https://naver.com/', icon: 'other' },
    ],
  },
  {
    id: 10,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    image: 'ProjectDetail.png',
    club: '토스 프로덕트 팀',
    serviceType: '웹 서비스',
    projectState: '서비스 진행중',
    projectPeriod: '2022.02.01 ~ 2023.08.09',
    techStack: 'React · TypeScript · Next · SpringBoot · Mysql ',
    describe,
    teamInfoBoxs,
    projectLink: [
      { url: 'https://github.com/', icon: 'github' },
      { url: 'https://figma.com/', icon: 'figma' },
      { url: 'https://naver.com/', icon: 'other' },
    ],
  },
  {
    id: 11,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    image: 'ProjectDetail.png',
    club: '토스 프로덕트 팀',
    serviceType: '웹 서비스',
    projectState: '서비스 진행중',
    projectPeriod: '2022.02.01 ~ 2023.08.09',
    techStack: 'React · TypeScript · Next · SpringBoot · Mysql ',
    describe,
    teamInfoBoxs,
    projectLink: [
      { url: 'https://github.com/', icon: 'github' },
      { url: 'https://figma.com/', icon: 'figma' },
      { url: 'https://naver.com/', icon: 'other' },
    ],
  },
  {
    id: 12,
    title: '토스 프로젝트',
    subTitle: '새롭고 달라진 금융 서비스를 만나보세요',
    tags: ['웹 서비스', '토스 프로덕트 팀'],
    image: 'ProjectDetail.png',
    club: '토스 프로덕트 팀',
    serviceType: '웹 서비스',
    projectState: '서비스 진행중',
    projectPeriod: '2022.02.01 ~ 2023.08.09',
    techStack: 'React · TypeScript · Next · SpringBoot · Mysql ',
    describe,
    teamInfoBoxs,
    projectLink: [
      { url: 'https://github.com/', icon: 'github' },
      { url: 'https://figma.com/', icon: 'figma' },
      { url: 'https://naver.com/', icon: 'other' },
    ],
  },
];
